{% set name = "azure-identity" %}
{% set version = "1.6.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: 2e70b00874e4f288e37804bc06bfaf216de8565c759594bf79cccfbf9ca2c78a

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - azure-core <2.0.0,>=1.0.0
    - cryptography >=2.1.4
    - msal <2.0.0,>=1.7.0
    - msal_extensions ~=0.3.0
    - python >=3.6
    - six >=1.12

test:
  imports:
    - azure.identity
    - azure.identity._credentials
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/identity/azure-identity
  summary: Microsoft Azure Identity Library for Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - marcelotrevisani
    - dhirschfeld
