{% set name = "azure-identity" %}
{% set version = "1.11.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.zip
  sha256: c3fc800af58b857e7faf0e310376e5ef10f5dad5090914cc42ffa6d7d23b6729

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv
  noarch: python

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - azure-core >=1.11.0,<2.0.0
    - cryptography >=2.5
    - msal >=1.12.0,<2.0.0
    - msal_extensions >=0.3.0,<2.0.0
    - python >=3.6
    - six >=1.12

test:
  imports:
    - azure.identity
    - azure.identity._credentials
  # commands:
  #   - pip check
  # requires:
  #   - pip

about:
  home: https://github.com/Azure/azure-sdk-for-python/tree/master/sdk/identity/azure-identity
  summary: Microsoft Azure Identity Library for Python
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - marcelotrevisani
    - dhirschfeld
